### ISSUE TITLE
Any way to switch to the canadian version of fanduel?

### ISSUE THREAD

**Issue by ayoubster** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#2]
I tried just changing the url to the canadian version at https://canada.sportsbook.fanduel.com/en/sports, but when the script tries to go and open the 'tennis' element, it can't find it since the all the sports are encoded with a unique number, in this case tennis is https://canada.sportsbook.fanduel.com/en/sports/navigation/1010.1/12781.3. 

Any tips on how I might be able to fix this?

**Comment by personal-coding** [comment]
You will likely need to make coding updates, as I only wrote the program to work on the US sportsbook. You could manually select the Tennis button. The program will give you an error message that it couldn't find that button on its own, but will still allow you to proceed. However, I can't guarantee that the XPath selectors will be the same, since the website is different.
